name: Python CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout my project
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py' ) --errors-only --disable=E0401
      - name: Launch Coverage
        run: |
          coverage run -m pytest
      - name: Report Coverage
        run : |
          coverage report
      - name: Run Load Test
        run: | 
          uvicorn application.main:app &
          locust --config=tests/.locust.conf --locustfile=tests/locustfile.py --headless
      - name: Install requirements
        run: |
          python -m pip install selenium
      - name : run code
        run: |
          python application/selenium_title.py
      

